# Generated by Django 4.1.7 on 2023-03-02 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toddoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2010-02-10'),
            preserve_default=False,
        ),
    ]
